module.exports = {
  mySidebar: [
    'index',
    'license',
    'requirements',
    'changelog',
    'videotutorials',
    {
      type: 'category',
      label: 'Client User Interface',
      collapsed: true,
      items: [
        'client-user-interface/main-menu',
        {
          type: 'category',
          label: 'File',
          collapsed: true,
          items: [
            'client-user-interface/file/file',
            'client-user-interface/file/import-settings',
            'client-user-interface/file/export-settings',
            'client-user-interface/file/task-scheduler',
            'client-user-interface/file/check-for-updates',
            'client-user-interface/file/client-settings',
            'client-user-interface/file/start-guide',
            'client-user-interface/file/manage-servers',
            'client-user-interface/file/open-translation-page',
            'client-user-interface/file/update-translation-page',
          ],
        },
        {
          type: 'category',
          label: 'Server',
          collapsed: true,
          items: [
            'client-user-interface/server/server',
            'client-user-interface/server/server-on-off', 
            {
              type: 'category',
              label: 'Main - Settings',
              collapsed: true,
              items: [
                'client-user-interface/server/main-settings',
                'client-user-interface/server/settings-default-flows',
                'client-user-interface/server/settings-users-logon',
                'client-user-interface/server/settings-log-settings',
                'client-user-interface/server/settings-email-settings',
                'client-user-interface/server/settings-proxy',
                'client-user-interface/server/settings-folders',
                'client-user-interface/server/settings-web-api',
                'client-user-interface/server/settings-web-client',
              ],
            },
            {
              type: 'category',
              label: 'Main - User Permissions',
              collapsed: true,
              items: [
                'client-user-interface/server/main-user-permissions',
                'client-user-interface/server/supported-permissions',
              ],
            },
              'client-user-interface/server/main-client-connections',   
              'client-user-interface/server/health-server-health',
              'client-user-interface/server/sla-uptime-outages-latency', 
              {
                type: 'category',
                label: 'Jobs - Jobs',
                collapsed: true,
                items: [
                  'client-user-interface/server/jobs-jobs',
                  {
                    type: 'category',
                    label: 'Job - Main Settings',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-main-settings',
                      'client-user-interface/server/job-variables',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Job - Triggers',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-triggers',
                      {
                        type: 'category',
                        label: 'Time Triggers',
                        collapsed: true,
                        items: [
                          'client-user-interface/server/time-triggers',
                          'client-user-interface/server/interval-time-trigger',
                          'client-user-interface/server/custom-time-trigger',
                          'client-user-interface/server/time-trigger-expiration',
                        ],
                      },
                      {
                        type: 'category',
                        label: 'Event Triggers',
                        collapsed: true,
                        items: [
                          'client-user-interface/server/event-triggers',
                          'client-user-interface/server/event-trigger-visualcron',
                          'client-user-interface/server/event-trigger-mft-server',
                          'client-user-interface/server/event-trigger-variable',
                          'client-user-interface/server/event-trigger-file',
                          'client-user-interface/server/event-trigger-remote-file',
                          'client-user-interface/server/event-trigger-cloud-file',
                          'client-user-interface/server/event-trigger-http-rest',
                          'client-user-interface/server/event-trigger-tcp',
                          'client-user-interface/server/event-trigger-sql',
                          'client-user-interface/server/event-trigger-powershell',
                          'client-user-interface/server/event-trigger-net-code-execute',
                          'client-user-interface/server/event-trigger-mail',
                          'client-user-interface/server/event-trigger-process',
                          'client-user-interface/server/event-trigger-service',
                          'client-user-interface/server/event-trigger-registry',
                          'client-user-interface/server/event-trigger-event-log',
                          'client-user-interface/server/event-trigger-msmq',
                          'client-user-interface/server/event-trigger-rss',
                          'client-user-interface/server/event-trigger-system-start-shutdown',
                          'client-user-interface/server/event-trigger-session-change',
                          'client-user-interface/server/event-trigger-custom',
                          'client-user-interface/server/event-trigger-printer',
                          'client-user-interface/server/event-trigger-network-change',
                          'client-user-interface/server/event-trigger-slack',
                          'client-user-interface/server/event-trigger-amqp',
                          'client-user-interface/server/event-trigger-sqs',
                          'client-user-interface/server/event-trigger-azure-queue-storage',
                          'client-user-interface/server/event-trigger-desktop',
                        ],
                      },
                    ],
                  },
                  'client-user-interface/server/job-time-exceptions',
                  'client-user-interface/server/job-conditions',

                  {
                    type: 'category',
                    label: 'Job - Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks',
                      'client-user-interface/server/job-tasks-loop-functionality',
                      'client-user-interface/server/job-tasks-file-filter',
                      'client-user-interface/server/job-tasks-remote-file-filter',
                      'client-user-interface/server/job-tasks-folder-filter',
                      {
                        type: 'category',
                        label: 'Task - Main Settings',
                        collapsed: true,
                        items: [
                          'client-user-interface/server/job-tasks-task-main-settings',
                          {
                            type: 'category',
                            label: 'Process Tasks',
                            collapsed: true,
                            items: [
                              'client-user-interface/server/job-tasks-task-main-settings',
                              'client-user-interface/server/job-tasks-task-process-execute',
                              'client-user-interface/server/job-tasks-task-process-remote-execute',
                              'client-user-interface/server/job-tasks-task-process-execute-script',
                              'client-user-interface/server/job-tasks-task-process-powershell',
                              'client-user-interface/server/job-tasks-task-process-kill',
                              'client-user-interface/server/job-tasks-task-process-remote-kill',
                              'client-user-interface/server/job-tasks-task-process-assembly-execute',
                              'client-user-interface/server/job-tasks-task-process-dot-net-code-execute',
                              'client-user-interface/server/job-tasks-task-process-unmanaged-dll-call',
                              'client-user-interface/server/job-tasks-task-process-as-400-command',
                            ],
                          },
                          {
                            type: 'category',
                            label: 'Net Tasks',
                            collapsed: true,
                            items: [
                              {
                              type: 'category',
                              label: 'Task Net - Web Macro',
                              collapsed: true,
                              items: [
                                'client-user-interface/server/job-tasks-net-tasks-task-net-web-macro',
                                'client-user-interface/server/job-tasks-net-tasks-element-path',
                                'client-user-interface/server/job-tasks-net-tasks-extract-data-step',
                                'client-user-interface/server/job-tasks-net-tasks-download-step',
                                'client-user-interface/server/job-tasks-net-tasks-download-by-search',
                                'client-user-interface/server/job-tasks-net-tasks-upload-step',
                                'client-user-interface/server/job-tasks-net-tasks-print-step',
                                'client-user-interface/server/job-tasks-net-tasks-proxy-step',
                                'client-user-interface/server/job-tasks-net-tasks-inject-js-step',
                                'client-user-interface/server/job-tasks-net-tasks-copy-link-address-step',
                                'client-user-interface/server/job-tasks-net-tasks-screenshot-step',
                              ],
                            },
                            'client-user-interface/server/job-tasks-net-tasks-task-net-http',
                            'client-user-interface/server/job-tasks-net-tasks-web-service-wcf-execute',
                            {
                              type: 'category',
                              label: 'Task Net - FTP/FTPS/SFTP/SCP',
                              collapsed: true,
                              items: [
                                'client-user-interface/server/job-tasks-net-tasks-task-net-ftp',
                                'client-user-interface/server/job-tasks-net-tasks-task-net-command-upload-files',
                                'client-user-interface/server/job-tasks-net-tasks-task-net-command-download-files',
                                'client-user-interface/server/job-tasks-net-tasks-task-net-command-list-files',
                                'client-user-interface/server/job-tasks-net-tasks-task-net-command-delete-files',
                                'client-user-interface/server/job-tasks-net-tasks-task-net-command-copy-move-files',
                                'client-user-interface/server/job-tasks-net-tasks-task-net-command-delete-folders',
                                'client-user-interface/server/job-tasks-net-tasks-task-net-command-create-folder',
                                'client-user-interface/server/job-tasks-net-tasks-task-net-command-change-folder',
                                'client-user-interface/server/job-tasks-net-tasks-task-net-command-rename-files',
                                'client-user-interface/server/job-tasks-net-tasks-task-net-command-rename-folder',
                                'client-user-interface/server/job-tasks-net-tasks-task-net-command-custom-command',
                              ],
                            },
                            'client-user-interface/server/job-tasks-net-tasks-task-net-ssh',
                            'client-user-interface/server/job-tasks-net-tasks-task-net-tcp',
                            'client-user-interface/server/job-tasks-net-tasks-task-net-ping',
                            'client-user-interface/server/job-tasks-net-tasks-task-net-check-port',
                            'client-user-interface/server/job-tasks-net-tasks-task-net-serial-send',
                            'client-user-interface/server/job-tasks-net-tasks-task-net-webdav-download',
                            'client-user-interface/server/job-tasks-net-tasks-task-net-webdav-upload',
                            'client-user-interface/server/job-tasks-net-tasks-task-net-webdav-copy-files',
                            'client-user-interface/server/job-tasks-net-tasks-task-net-webdav-delete',
                            'client-user-interface/server/job-tasks-net-tasks-task-net-webdav-create-folder',
                            ],
                          },
                        ],
                      },
                      {
                      type: 'category',
                      label: 'Messaging Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-email',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-email-get-headers',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-email-get-messages',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-email-get-single-message',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-email-delete-single-message',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-email-delete-messages',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-xendapp',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-syslog',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-pushbullet-send-message',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-pushbullet-send-sms',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-pushbullet-send-link',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-pushbullet-send-file',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-pushbullet-upload-file',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-telegram-send-bot-message',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-telegram-user-send-message',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-slack-send-message',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-amqp-send-message',
                        'client-user-interface/server/job-tasks-messaging-tasks-task-messaging-sns-publish-message',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Social Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-tweet',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-reply-tweet',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-get-tweet',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-delete-tweet',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-follow-unfollow-tweet',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-send-direct-message',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-retweet-undo-retweet',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-like-undo-like',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-search-tweets',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-get-messages',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-get-timeline',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-get-mentions',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-get-friends',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-twitter-get-followers',
                        'client-user-interface/server/job-tasks-social-tasks-task-social-facebook-publish',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Database Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-database-tasks-task-database-sql',
                        'client-user-interface/server/job-tasks-database-tasks-task-database-execute-dts-package',
                        'client-user-interface/server/job-tasks-database-tasks-task-database-execute-ssis-package',
                        'client-user-interface/server/job-tasks-database-tasks-task-database-execute-ssisdb-package',
                        'client-user-interface/server/job-tasks-database-tasks-task-database-ssrs',
                        'client-user-interface/server/job-tasks-database-tasks-task-database-sync-tables',
                        'client-user-interface/server/job-tasks-database-tasks-task-database-big-query-fill-table',
                        'client-user-interface/server/job-tasks-database-tasks-task-database-big-query-run-query',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Encryption Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-encryption-tasks-task-encryption-pgp-encrypt',
                        'client-user-interface/server/job-tasks-encryption-tasks-task-encryption-pgp-decrypt',
                        'client-user-interface/server/job-tasks-encryption-tasks-task-encryption-encrypt-symmetric',
                        'client-user-interface/server/job-tasks-encryption-tasks-task-encryption-decrypt-symmetric',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'String Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-string-tasks-task-string-json-filter',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'File Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-file-tasks-task-file-copy-files',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-sync',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-archive-compress',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-archive-extract',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-list-files',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-read-file',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-write-file',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-touch-file',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-delete-file',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-rename-file',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-concatenate-files',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-list-folders',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-create-folder',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-rename-folder',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-delete-folders',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-get-checksum',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-set-attributes',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-change-owner',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-set-file-permissions',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-set-folder-permissions',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-base64-encode',
                        'client-user-interface/server/job-tasks-file-tasks-task-file-base64-decode',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Image Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-image-tasks-task-image-adjust',
                        'client-user-interface/server/job-tasks-image-tasks-task-image-convert',
                        'client-user-interface/server/job-tasks-image-tasks-task-image-crop',
                        'client-user-interface/server/job-tasks-image-tasks-task-image-filter',
                        'client-user-interface/server/job-tasks-image-tasks-task-image-flip',
                        'client-user-interface/server/job-tasks-image-tasks-task-image-get-exif-data',
                        'client-user-interface/server/job-tasks-image-tasks-task-image-join',
                        'client-user-interface/server/job-tasks-image-tasks-task-image-overlay',
                        'client-user-interface/server/job-tasks-image-tasks-task-image-profile-conversion',
                        'client-user-interface/server/job-tasks-image-tasks-task-image-resize',
                        'client-user-interface/server/job-tasks-image-tasks-task-image-rotate',
                        'client-user-interface/server/job-tasks-image-tasks-task-image-scan-document-local',
                        'client-user-interface/server/job-tasks-image-tasks-task-image-scan-document-cloud',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'XML Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-xml-tasks-task-xml-read-node',
                        'client-user-interface/server/job-tasks-xml-tasks-task-xml-create-node',
                        'client-user-interface/server/job-tasks-xml-tasks-task-xml-edit-node',
                        'client-user-interface/server/job-tasks-xml-tasks-task-xml-delete-node',
                        'client-user-interface/server/job-tasks-xml-tasks-task-xml-transform',
                        'client-user-interface/server/job-tasks-xml-tasks-task-xml-transform',
                        'client-user-interface/server/job-tasks-xml-tasks-task-xml-sign',
                        'client-user-interface/server/job-tasks-xml-tasks-task-xml-verify',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Service Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-service-tasks-task-service-start-service',
                        'client-user-interface/server/job-tasks-service-tasks-task-service-stop-service',
                        'client-user-interface/server/job-tasks-service-tasks-task-service-restart-service',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Office Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-office-tasks-task-office-excel-get-cell',
                        'client-user-interface/server/job-tasks-office-tasks-task-office-excel-set-cell',
                        'client-user-interface/server/job-tasks-office-tasks-task-office-excel-convert',
                        'client-user-interface/server/job-tasks-office-tasks-task-office-excel-get-row-count',
                        'client-user-interface/server/job-tasks-office-tasks-task-office-excel-create',
                        'client-user-interface/server/job-tasks-office-tasks-task-office-excel-recalculate',
                        'client-user-interface/server/job-tasks-office-tasks-task-office-office-macro',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Reporting Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-reporting-tasks-task-reporting-crystal-reports',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'System Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-system-tasks-task-system-registry',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-shutdown',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-restart',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-lock-workstation',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-unlock-workstation',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-logoff',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-hibernate',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-standby',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-wakeup',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-wakeup-on-lan',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-control-monitor',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-print-document',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-windows-update',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-environment-get-variable',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-environment-set-variable',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-environment-append-variable',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-environment-list-variables',
                        'client-user-interface/server/job-tasks-system-tasks-task-system-environment-delete-variables',                  
                      ],
                    },
                    {
                      type: 'category',
                      label: 'System  Restore Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-system-restore-tasks-task-system-restore-create-restore-point',
                        'client-user-interface/server/job-tasks-system-restore-tasks-task-system-restore-perform-system-restore',
                        'client-user-interface/server/job-tasks-system-restore-tasks-task-system-restore-list-restore-points',                  
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Event Log Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-event-log-tasks-task-event-log-event-log-read',  
                        'client-user-interface/server/job-tasks-event-log-tasks-task-event-log-event-log-write',              
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Interactivity Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks-interactivity-tasks-task-interactivity-popup',
                        'client-user-interface/server/job-tasks-interactivity-tasks-task-interactivity-desktop-macro',
                        'client-user-interface/server/job-tasks-interactivity-tasks-task-interactivity-robot-task',
                        'client-user-interface/server/job-tasks-interactivity-tasks-task-interactivity-send-keys',
                        'client-user-interface/server/job-tasks-interactivity-tasks-task-interactivity-wait',
                        'client-user-interface/server/job-tasks-interactivity-tasks-task-interactivity-play-sound',                
                      ],
                    },
                    {
                    type: 'category',
                    label: 'Internal Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks-internal-tasks-task-internal-job-task-control',
                      'client-user-interface/server/job-tasks-internal-tasks-task-internal-export-settings',
                      'client-user-interface/server/job-tasks-internal-tasks-task-internal-set-job-variable',
                      'client-user-interface/server/job-tasks-internal-tasks-task-internal-set-user-variable', 
                      'client-user-interface/server/job-tasks-internal-tasks-task-internal-calculate-variable',
                      'client-user-interface/server/job-tasks-internal-tasks-task-internal-remove-variable',  
                      'client-user-interface/server/job-tasks-internal-tasks-task-internal-report',                     
                    ],
                  },
                    ],
                  },
                  'client-user-interface/server/job-timeout',
                  'client-user-interface/server/job-notifications',
                  'client-user-interface/server/job-flow',
                  'client-user-interface/server/job-agent-distribution',
                  'client-user-interface/server/roi-return-on-investment',
                ],
              },
              'client-user-interface/server/jobs-failed-jobs',
              'client-user-interface/server/jobs-running-jobs',
              'client-user-interface/server/global-certificates',
              {
                type: 'category',
                label: 'Global - Conditions',
                collapsed: true,
                items: [
                  'client-user-interface/server/global-conditions',
                  'client-user-interface/server/global-main-settings',
                  {
                    type: 'category',
                    label: 'Conditions - Conditions',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/conditions-conditions',
                      'client-user-interface/server/condition-visualcron',
                      'client-user-interface/server/condition-file',
                      'client-user-interface/server/condition-folder',
                      'client-user-interface/server/condition-process',
                      'client-user-interface/server/condition-dot-net',
                    ],
                  },
                  'client-user-interface/server/conditions-actions',
                ],
              },
              {
                type: 'category',
                label: 'Global - Connections',
                collapsed: true,
                items: [
                  'client-user-interface/server/global-connections',
                  'client-user-interface/server/connection-ftp',
                  'client-user-interface/server/connection-sftp',
                  'client-user-interface/server/connection-scp',
                  'client-user-interface/server/connection-ssh',
                  'client-user-interface/server/connection-tcp',
                  'client-user-interface/server/connection-smtp',
                  'client-user-interface/server/connection-pop3',
                  'client-user-interface/server/connection-imap4',
                  'client-user-interface/server/connection-exchange-ews',
                  'client-user-interface/server/connection-exchange-webdav',
                  'client-user-interface/server/connection-webdav',
                  'client-user-interface/server/connection-sql',
                  'client-user-interface/server/connection-ssrs',
                  'client-user-interface/server/connection-amazon',
                  'client-user-interface/server/connection-microsoft-azure',
                  'client-user-interface/server/connection-dropbox',
                  'client-user-interface/server/connection-google-drive',
                  'client-user-interface/server/connection-google-cloud',
                  'client-user-interface/server/connection-onedrive',
                  'client-user-interface/server/connection-office365',
                  'client-user-interface/server/connection-box',
                  'client-user-interface/server/connection-visualcron',
                  'client-user-interface/server/connection-sharepoint',
                  'client-user-interface/server/connection-xendapp',
                  'client-user-interface/server/connection-pushbullet',
                  'client-user-interface/server/connection-telegram',
                  'client-user-interface/server/connection-twitter',
                  'client-user-interface/server/connection-crystalreports',
                  'client-user-interface/server/connection-vmware',
                  'client-user-interface/server/connection-dynamics-crm',
                  'client-user-interface/server/connection-as400',
                  'client-user-interface/server/connection-sap',
                  'client-user-interface/server/connection-amqp',
                  'client-user-interface/server/connection-slack',
                  'client-user-interface/server/connection-informatica',
                  'client-user-interface/server/connection-telnet',
                  'client-user-interface/server/connection-facebook',
                  'client-user-interface/server/connection-peoplesoft',
                  'client-user-interface/server/connection-ibm-cognos-analytics',
                ],
              },
              'client-user-interface/server/global-credentials',
              'client-user-interface/server/global-network-drives',
              'client-user-interface/server/global-notifications',
              'client-user-interface/server/global-pgp-key-rings',
              'client-user-interface/server/global-time-exceptions',
              {
                type: 'category',
                label: 'Global Variables',
                collapsed: true,
                items: [
                  'client-user-interface/server/global-variables',
                  'client-user-interface/server/global-date-time-variables',
                ],
              }, 
              'client-user-interface/server/global-task-repository',
              'client-user-interface/server/information-log',
              'client-user-interface/server/information-server-info',
              'client-user-interface/server/information-license',
          ],
        },
      ],
    },
    'debugging-and-logging',
    'security',
    {
      type: 'category',
      label: 'Commands, Scripts, and Third Party Tools',
      collapsed: true,
      items: [
        'commands/commands-scripts-third-party-tools',
        'commands/commands-and-batch-files',
        'commands/scripts',
      ],
    },    
    {
      type: 'category',
      label: 'FAQ',
      collapsed: true,
      items: [
        'faq/install-upgrade-procedure',
        'faq/visualcron-using-so-much-memory',
        'faq/installation-file-so-big',
        'faq/firewall-warn-internet-access',
        'faq/add-edit-delete-lag-time',
        'faq/support-visualcron',
        'faq/move-visualcron-active-license-new-server',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: true,
      items: [
        'examples/setting-a-job-to-run-every-second-or-five-minutes',
        'examples/using-arguments-parameters-for-a-job',
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      collapsed: true,
      items: [
        'troubleshooting/job-does-not-run',
        'troubleshooting/i-cant-start-visualcron',
        'troubleshooting/i-cant-connect-to-visualcron-server',
        'troubleshooting/forgot-my-password',
        'troubleshooting/missing-system-file-perfc009',
        'troubleshooting/i-cant-open-visualcron-documentation',
        'troubleshooting/i-cant-download-visualcron',
        'troubleshooting/windows-98-me-errors',
        'troubleshooting/client-timeouts',
        'troubleshooting/windows-command-does-not-execute',
        'troubleshooting/settings-do-not-work',
        'troubleshooting/external-link-errors',
        'troubleshooting/installation-errors',
        'troubleshooting/wmi-is-broken',
        'troubleshooting/visualcron-service-does-not-start-automatically',
        'troubleshooting/upgrade-setup-fails',
        'troubleshooting/server-mode-ssl-certificate',
        'troubleshooting/error-114-in-sftp-task',
        'troubleshooting/uninstall-fails',
        'troubleshooting/file-not-found-access-denied',
        'troubleshooting/error-loading-server-settings',
      ],
    },
    {
      type: 'category',
      label: 'Definitions',
      collapsed: true,
      items: [
        'general-definitions',
        'visualcron-specific-definitions',
        'documentation-format',
      ],
    },
  ],
};
