/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'core-concepts' }],
    },
    {
      type: 'category',
      label: 'Server',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'server' }],
    },
    {
      type: 'category',
      label: 'Client',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'client' }],
    },
    {
      type: 'category',
      label: 'Infrastructure',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'infrastructure' }],
    },
    {
      type: 'category',
      label: 'Tasks',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'tasks' }],
    },
    {
      type: 'category',
      label: 'Triggers',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'triggers' }],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'integrations' }],
    },
    {
      type: 'category',
      label: 'Connections',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'connections' }],
    },
    {
      type: 'category',
      label: 'Global Objects',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'global-objects' }],
    },
    {
      type: 'category',
      label: 'Tools',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'tools' }],
    },
    {
      type: 'category',
      label: 'Reports',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'reports' }],
    },
    {
      type: 'category',
      label: 'Import / Export',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'import-export' }],
    },
    {
      type: 'category',
      label: 'API',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'troubleshooting' }],
    },
  ],
};
