module.exports = {
  mySidebar: [
    'index',
    'license',
    'requirements',
    'changelog',
    //'videotutorials',
    {
      type: 'category',
      label: 'Get VisualCron',
      collapsed: true,
      items: [
        'get-visualcron/get-visualcron',
        'get-visualcron/download-install-upgrade-uninstall',
        'get-visualcron/assembly-resolver',
        'get-visualcron/remote-silent-customized-installation',
        'get-visualcron/multiple-clients-on-same-machine',
        'get-visualcron/Upgrading Versions',
        'get-visualcron/language-management',
        'get-visualcron/custom-branding',
      ],
    },
    {
      type: 'category',
      label: 'Using VisualCron',
      collapsed: true,
      items: [
        'using-visualcron/using-visualcron',
        'using-visualcron/how-does-visualcron-work',
        'using-visualcron/visualcron-server',
        'using-visualcron/login',
        'using-visualcron/limitations',
        {
          type: 'category',
          label: 'Licensing',
          collapsed: true,
          items: [
            'using-visualcron/licensing',
            'using-visualcron/trial-time',
            'using-visualcron/choosing-the-right-license',
            'using-visualcron/basic-vs-pro-edition',
            'using-visualcron/license-and-activation',
            {
              type: 'category',
              label: 'Maintenance',
              collapsed: true,
              items: [
                'using-visualcron/maintenance',
                'using-visualcron/maintenance-expiration',
                'using-visualcron/license-validation',
              ],
            },
            'using-visualcron/move-a-license',
          ],
        },
        {
          type: 'category',
          label: 'Using VisualCron in a Clusted Environment',
          collapsed: true,
          items: [
            'using-visualcron/using-visualcron-in-a-clustered-environment',
            {
              type: 'category',
              label: 'Installing Windows Failover Cluster',
              collapsed: true,
              items: [
                'using-visualcron/installing-windows-failover-cluster',
                'using-visualcron/configure-roles-fcap',
                'using-visualcron/configure-roles-nodes',
                'using-visualcron/create-iscsi-network-drive',
                'using-visualcron/connecting-to-iscsi-network-drives',
                'using-visualcron/create-the-failover-cluster', 
              ],
            },
            {
              type: 'category',
              label: 'Install and Setup VisualCron on Failover Cluster',
              collapsed: true,
              items: [
                'using-visualcron/install-and-setup-visualcron-on-failover-cluster',
                'using-visualcron/create-iscsi-drive-with-existing-target',
                'using-visualcron/add-new-shared-drive-to-cluster',
                'using-visualcron/install-visualcron-on-both-nodes',
                'using-visualcron/add-shared-drive-to-cluster',
                'using-visualcron/add-generic-service',
                'using-visualcron/manually-changing-current-node',
                'using-visualcron/setup-failover-generic-service-properties',
                'using-visualcron/individual-node-activation',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Interacting with VisualCron',
          collapsed: true,
          items: [
            'using-visualcron/visualcron-client',
            'using-visualcron/starting-visualcron-client',
            'using-visualcron/visualcron-tray-client',
            'using-visualcron/visualcron-web-client',
            'using-visualcron/installation-of-web-client',
            'using-visualcron/enable-windows-authentication',
            'using-visualcron/mobile-app',
            'using-visualcron/visualcron-api',
            'using-visualcron/dot-net-csharp-vbnet',
            'using-visualcron/powershell',
            'using-visualcron/visualcron-web-api',
            'using-visualcron/vccommand',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Client User Interface',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Main Menu',
          collapsed: true,
          items: [
            'client-user-interface/main-menu',
        {
          type: 'category',
          label: 'File',
          collapsed: true,
          items: [
            'client-user-interface/file/file',
            'client-user-interface/file/import-settings',
            'client-user-interface/file/export-settings',
            'client-user-interface/file/task-scheduler',
            'client-user-interface/file/check-for-updates',
            'client-user-interface/file/client-settings',
            'client-user-interface/file/start-guide',
            'client-user-interface/file/manage-servers',
            'client-user-interface/file/open-translation-page',
            'client-user-interface/file/update-translation-page',
          ],
        },
        {
          type: 'category',
          label: 'Server',
          collapsed: true,
          items: [
            'client-user-interface/server/server',
            'client-user-interface/server/server-on-off', 
            {
              type: 'category',
              label: 'Main - Settings',
              collapsed: true,
              items: [
                'client-user-interface/server/main-settings',
                'client-user-interface/server/settings-default-flows',
                'client-user-interface/server/settings-users-logon',
                'client-user-interface/server/settings-log-settings',
                'client-user-interface/server/settings-email-settings',
                'client-user-interface/server/settings-proxy',
                'client-user-interface/server/settings-folders',
                'client-user-interface/server/settings-web-api',
                'client-user-interface/server/settings-web-client',
              ],
            },
            {
              type: 'category',
              label: 'Main - User Permissions',
              collapsed: true,
              items: [
                'client-user-interface/server/main-user-permissions',
                'client-user-interface/server/supported-permissions',
              ],
            },
              'client-user-interface/server/main-client-connections',   
              'client-user-interface/server/health-server-health',
              'client-user-interface/server/sla-uptime-outages-latency', 
              {
                type: 'category',
                label: 'Jobs - Jobs',
                collapsed: true,
                items: [
                  'client-user-interface/server/jobs-jobs',
                  {
                    type: 'category',
                    label: 'Job - Main Settings',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-main-settings',
                      'client-user-interface/server/job-variables',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Job - Triggers',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-triggers',
                      {
                        type: 'category',
                        label: 'Time Triggers',
                        collapsed: true,
                        items: [
                          'client-user-interface/server/time-triggers',
                          'client-user-interface/server/interval-time-trigger',
                          'client-user-interface/server/custom-time-trigger',
                          'client-user-interface/server/time-trigger-expiration',
                        ],
                      },
                      {
                        type: 'category',
                        label: 'Event Triggers',
                        collapsed: true,
                        items: [
                          'client-user-interface/server/event-triggers',
                          'client-user-interface/server/event-trigger-visualcron',
                          'client-user-interface/server/event-trigger-mft-server',
                          'client-user-interface/server/event-trigger-variable',
                          'client-user-interface/server/event-trigger-file',
                          'client-user-interface/server/event-trigger-remote-file',
                          'client-user-interface/server/event-trigger-cloud-file',
                          'client-user-interface/server/event-trigger-http-rest',
                          'client-user-interface/server/event-trigger-tcp',
                          'client-user-interface/server/event-trigger-sql',
                          'client-user-interface/server/event-trigger-powershell',
                          'client-user-interface/server/event-trigger-net-code-execute',
                          'client-user-interface/server/event-trigger-mail',
                          'client-user-interface/server/event-trigger-process',
                          'client-user-interface/server/event-trigger-service',
                          'client-user-interface/server/event-trigger-registry',
                          'client-user-interface/server/event-trigger-event-log',
                          'client-user-interface/server/event-trigger-msmq',
                          'client-user-interface/server/event-trigger-rss',
                          'client-user-interface/server/event-trigger-system-start-shutdown',
                          'client-user-interface/server/event-trigger-session-change',
                          'client-user-interface/server/event-trigger-custom',
                          'client-user-interface/server/event-trigger-printer',
                          'client-user-interface/server/event-trigger-network-change',
                          'client-user-interface/server/event-trigger-slack',
                          'client-user-interface/server/event-trigger-amqp',
                          'client-user-interface/server/event-trigger-sqs',
                          'client-user-interface/server/event-trigger-azure-queue-storage',
                          'client-user-interface/server/event-trigger-desktop',
                        ],
                      },
                    ],
                  },
                  'client-user-interface/server/job-time-exceptions',
                  'client-user-interface/server/job-conditions',

                  {
                    type: 'category',
                    label: 'Job - Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks',
                      'client-user-interface/server/job-tasks-loop-functionality',
                      'client-user-interface/server/job-tasks-file-filter',
                      'client-user-interface/server/job-tasks-remote-file-filter',
                      'client-user-interface/server/job-tasks-cloud-remote-file-filter',
                      'client-user-interface/server/job-tasks-folder-filter',
                      {
                        type: 'category',
                        label: 'Task - Main Settings',
                        collapsed: true,
                        items: [
                          'client-user-interface/server/job-tasks-task-main-settings',
                          {
                            type: 'category',
                            label: 'Process Tasks',
                            collapsed: true,
                            items: [
                              'client-user-interface/server/job-tasks-task-main-settings',
                              'client-user-interface/server/job-tasks-task-process-execute',
                              'client-user-interface/server/job-tasks-task-process-remote-execute',
                              'client-user-interface/server/job-tasks-task-process-execute-script',
                              'client-user-interface/server/job-tasks-task-process-powershell',
                              'client-user-interface/server/job-tasks-task-process-kill',
                              'client-user-interface/server/job-tasks-task-process-remote-kill',
                              'client-user-interface/server/job-tasks-task-process-assembly-execute',
                              'client-user-interface/server/job-tasks-task-process-dot-net-code-execute',
                              'client-user-interface/server/job-tasks-task-process-unmanaged-dll-call',
                              'client-user-interface/server/job-tasks-task-process-as-400-command',
                            ],
                          },
                          {
                            type: 'category',
                            label: 'Net Tasks',
                            collapsed: true,
                            items: [
                              {
                              type: 'category',
                              label: 'Task Net - Web Macro',
                              collapsed: true,
                              items: [
                                'client-user-interface/server/job-tasks/net-tasks/web-macro',
                                'client-user-interface/server/job-tasks/net-tasks/element-path',
                                'client-user-interface/server/job-tasks/net-tasks/extract-data-step',
                                'client-user-interface/server/job-tasks/net-tasks/download-step',
                                'client-user-interface/server/job-tasks/net-tasks/download-by-search',
                                'client-user-interface/server/job-tasks/net-tasks/upload-step',
                                'client-user-interface/server/job-tasks/net-tasks/print-step',
                                'client-user-interface/server/job-tasks/net-tasks/proxy-step',
                                'client-user-interface/server/job-tasks/net-tasks/inject-js-step',
                                'client-user-interface/server/job-tasks/net-tasks/copy-link-address-step',
                                'client-user-interface/server/job-tasks/net-tasks/screenshot-step',
                              ],
                            },
                            'client-user-interface/server/job-tasks/net-tasks/http',
                            'client-user-interface/server/job-tasks/net-tasks/web-service-wcf-execute',
                            {
                              type: 'category',
                              label: 'Task Net - FTP/FTPS/SFTP/SCP',
                              collapsed: true,
                              items: [
                                'client-user-interface/server/job-tasks/net-tasks/ftp',
                                'client-user-interface/server/job-tasks/net-tasks/command-upload-files',
                                'client-user-interface/server/job-tasks/net-tasks/command-download-files',
                                'client-user-interface/server/job-tasks/net-tasks/command-list-files',
                                'client-user-interface/server/job-tasks/net-tasks/command-delete-files',
                                'client-user-interface/server/job-tasks/net-tasks/command-copy-move-files',
                                'client-user-interface/server/job-tasks/net-tasks/command-delete-folders',
                                'client-user-interface/server/job-tasks/net-tasks/command-create-folder',
                                'client-user-interface/server/job-tasks/net-tasks/command-change-folder',
                                'client-user-interface/server/job-tasks/net-tasks/command-rename-files',
                                'client-user-interface/server/job-tasks/net-tasks/command-rename-folder',
                                'client-user-interface/server/job-tasks/net-tasks/command-custom-command',
                              ],
                            },
                            'client-user-interface/server/job-tasks/net-tasks/ssh',
                            'client-user-interface/server/job-tasks/net-tasks/tcp',
                            'client-user-interface/server/job-tasks/net-tasks/ping',
                            'client-user-interface/server/job-tasks/net-tasks/check-port',
                            'client-user-interface/server/job-tasks/net-tasks/serial-send',
                            'client-user-interface/server/job-tasks/net-tasks/webdav-download',
                            'client-user-interface/server/job-tasks/net-tasks/webdav-upload',
                            'client-user-interface/server/job-tasks/net-tasks/webdav-copy-files',
                            'client-user-interface/server/job-tasks/net-tasks/webdav-delete',
                            'client-user-interface/server/job-tasks/net-tasks/webdav-create-folder',
                            ],
                          },
                        ],
                      },
                      {
                      type: 'category',
                      label: 'Messaging Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/messaging-tasks/email',
                        'client-user-interface/server/job-tasks/messaging-tasks/email-get-headers',
                        'client-user-interface/server/job-tasks/messaging-tasks/email-get-messages',
                        'client-user-interface/server/job-tasks/messaging-tasks/email-get-single-message',
                        'client-user-interface/server/job-tasks/messaging-tasks/email-delete-single-message',
                        'client-user-interface/server/job-tasks/messaging-tasks/email-delete-messages',
                        'client-user-interface/server/job-tasks/messaging-tasks/xendapp',
                        'client-user-interface/server/job-tasks/messaging-tasks/syslog',
                        'client-user-interface/server/job-tasks/messaging-tasks/pushbullet-send-message',
                        'client-user-interface/server/job-tasks/messaging-tasks/pushbullet-send-sms',
                        'client-user-interface/server/job-tasks/messaging-tasks/pushbullet-send-link',
                        'client-user-interface/server/job-tasks/messaging-tasks/pushbullet-send-file',
                        'client-user-interface/server/job-tasks/messaging-tasks/pushbullet-upload-file',
                        'client-user-interface/server/job-tasks/messaging-tasks/telegram-send-bot-message',
                        'client-user-interface/server/job-tasks/messaging-tasks/telegram-user-send-message',
                        'client-user-interface/server/job-tasks/messaging-tasks/slack-send-message',
                        'client-user-interface/server/job-tasks/messaging-tasks/amqp-send-message',
                        'client-user-interface/server/job-tasks/messaging-tasks/sns-publish-message',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Social Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/social-tasks/twitter-tweet',
                        'client-user-interface/server/job-tasks/social-tasks/twitter-reply-tweet',
                        'client-user-interface/server/job-tasks/social-tasks/twitter-get-tweet',
                        'client-user-interface/server/job-tasks/social-tasks/twitter-delete-tweet',
                        'client-user-interface/server/job-tasks/social-tasks/twitter-follow-unfollow-tweet',
                        'client-user-interface/server/job-tasks/social-tasks/twitter-send-direct-message',
                        'client-user-interface/server/job-tasks/social-tasks/twitter-retweet-undo-retweet',
                        'client-user-interface/server/job-tasks/social-tasks/twitter-like-undo-like',
                        'client-user-interface/server/job-tasks/social-tasks/twitter-search-tweets',
                        'client-user-interface/server/job-tasks/social-tasks/twitter-get-messages',
                        'client-user-interface/server/job-tasks/social-tasks/twitter-get-timeline',
                        'client-user-interface/server/job-tasks/social-tasks/twitter-get-mentions',
                        'client-user-interface/server/job-tasks/social-tasks/twitter-get-friends',
                        'client-user-interface/server/job-tasks/social-tasks/twitter-get-followers',
                        'client-user-interface/server/job-tasks/social-tasks/facebook-publish',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Database Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/database-tasks/sql',
                        'client-user-interface/server/job-tasks/database-tasks/execute-dts-package',
                        'client-user-interface/server/job-tasks/database-tasks/execute-ssis-package',
                        'client-user-interface/server/job-tasks/database-tasks/execute-ssisdb-package',
                        'client-user-interface/server/job-tasks/database-tasks/ssrs',
                        'client-user-interface/server/job-tasks/database-tasks/sync-tables',
                        'client-user-interface/server/job-tasks/database-tasks/big-query-fill-table',
                        'client-user-interface/server/job-tasks/database-tasks/big-query-run-query',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Encryption Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/encryption-tasks/pgp-encrypt',
                        'client-user-interface/server/job-tasks/encryption-tasks/pgp-decrypt',
                        'client-user-interface/server/job-tasks/encryption-tasks/encrypt-symmetric',
                        'client-user-interface/server/job-tasks/encryption-tasks/decrypt-symmetric',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'String Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/string-tasks/json-filter',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'File Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/file-tasks/copy-files',
                        'client-user-interface/server/job-tasks/file-tasks/sync',
                        'client-user-interface/server/job-tasks/file-tasks/archive-compress',
                        'client-user-interface/server/job-tasks/file-tasks/archive-extract',
                        'client-user-interface/server/job-tasks/file-tasks/list-files',
                        'client-user-interface/server/job-tasks/file-tasks/read-file',
                        'client-user-interface/server/job-tasks/file-tasks/write-file',
                        'client-user-interface/server/job-tasks/file-tasks/touch-file',
                        'client-user-interface/server/job-tasks/file-tasks/delete-file',
                        'client-user-interface/server/job-tasks/file-tasks/rename-file',
                        'client-user-interface/server/job-tasks/file-tasks/concatenate-files',
                        'client-user-interface/server/job-tasks/file-tasks/list-folders',
                        'client-user-interface/server/job-tasks/file-tasks/create-folder',
                        'client-user-interface/server/job-tasks/file-tasks/rename-folder',
                        'client-user-interface/server/job-tasks/file-tasks/delete-folders',
                        'client-user-interface/server/job-tasks/file-tasks/get-checksum',
                        'client-user-interface/server/job-tasks/file-tasks/set-attributes',
                        'client-user-interface/server/job-tasks/file-tasks/change-owner',
                        'client-user-interface/server/job-tasks/file-tasks/set-file-permissions',
                        'client-user-interface/server/job-tasks/file-tasks/set-folder-permissions',
                        'client-user-interface/server/job-tasks/file-tasks/base64-encode',
                        'client-user-interface/server/job-tasks/file-tasks/base64-decode',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Image Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/image-tasks/adjust',
                        'client-user-interface/server/job-tasks/image-tasks/convert',
                        'client-user-interface/server/job-tasks/image-tasks/crop',
                        'client-user-interface/server/job-tasks/image-tasks/filter',
                        'client-user-interface/server/job-tasks/image-tasks/flip',
                        'client-user-interface/server/job-tasks/image-tasks/get-exif-data',
                        'client-user-interface/server/job-tasks/image-tasks/join',
                        'client-user-interface/server/job-tasks/image-tasks/overlay',
                        'client-user-interface/server/job-tasks/image-tasks/profile-conversion',
                        'client-user-interface/server/job-tasks/image-tasks/resize',
                        'client-user-interface/server/job-tasks/image-tasks/rotate',
                        'client-user-interface/server/job-tasks/image-tasks/scan-document-local',
                        'client-user-interface/server/job-tasks/image-tasks/scan-document-cloud',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'XML Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/xml-tasks/read-node',
                        'client-user-interface/server/job-tasks/xml-tasks/create-node',
                        'client-user-interface/server/job-tasks/xml-tasks/edit-node',
                        'client-user-interface/server/job-tasks/xml-tasks/delete-node',
                        'client-user-interface/server/job-tasks/xml-tasks/transform',
                        'client-user-interface/server/job-tasks/xml-tasks/validate',
                        'client-user-interface/server/job-tasks/xml-tasks/sign',
                        'client-user-interface/server/job-tasks/xml-tasks/verify',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Service Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/service-tasks/start-service',
                        'client-user-interface/server/job-tasks/service-tasks/stop-service',
                        'client-user-interface/server/job-tasks/service-tasks/restart-service',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Office Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/office-tasks/excel-get-cell',
                        'client-user-interface/server/job-tasks/office-tasks/excel-set-cell',
                        'client-user-interface/server/job-tasks/office-tasks/excel-convert',
                        'client-user-interface/server/job-tasks/office-tasks/excel-get-row-count',
                        'client-user-interface/server/job-tasks/office-tasks/excel-create',
                        'client-user-interface/server/job-tasks/office-tasks/excel-recalculate',
                        'client-user-interface/server/job-tasks/office-tasks/office-macro',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Reporting Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/reporting-tasks/crystal-reports',
                      ],
                    },
                    {
                      type: 'category',
                      label: 'System Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/system-tasks/registry',
                        'client-user-interface/server/job-tasks/system-tasks/shutdown',
                        'client-user-interface/server/job-tasks/system-tasks/restart',
                        'client-user-interface/server/job-tasks/system-tasks/lock-workstation',
                        'client-user-interface/server/job-tasks/system-tasks/unlock-workstation',
                        'client-user-interface/server/job-tasks/system-tasks/logoff',
                        'client-user-interface/server/job-tasks/system-tasks/hibernate',
                        'client-user-interface/server/job-tasks/system-tasks/standby',
                        'client-user-interface/server/job-tasks/system-tasks/wakeup',
                        'client-user-interface/server/job-tasks/system-tasks/wakeup-on-lan',
                        'client-user-interface/server/job-tasks/system-tasks/control-monitor',
                        'client-user-interface/server/job-tasks/system-tasks/print-document',
                        'client-user-interface/server/job-tasks/system-tasks/windows-update',
                        'client-user-interface/server/job-tasks/system-tasks/environment-get-variable',
                        'client-user-interface/server/job-tasks/system-tasks/environment-set-variable',
                        'client-user-interface/server/job-tasks/system-tasks/environment-append-variable',
                        'client-user-interface/server/job-tasks/system-tasks/environment-list-variables',
                        'client-user-interface/server/job-tasks/system-tasks/environment-delete-variables',                  
                      ],
                    },
                    {
                      type: 'category',
                      label: 'System Restore Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/system-restore-tasks/create-restore-point',
                        'client-user-interface/server/job-tasks/system-restore-tasks/perform-system-restore',
                        'client-user-interface/server/job-tasks/system-restore-tasks/list-restore-points',                  
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Event Log Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/event-log-tasks/event-log-read',  
                        'client-user-interface/server/job-tasks/event-log-tasks/event-log-write',              
                      ],
                    },
                    {
                      type: 'category',
                      label: 'Interactivity Tasks',
                      collapsed: true,
                      items: [
                        'client-user-interface/server/job-tasks/interactivity-tasks/popup',
                        'client-user-interface/server/job-tasks/interactivity-tasks/desktop-macro',
                        'client-user-interface/server/job-tasks/interactivity-tasks/robot-task',
                        'client-user-interface/server/job-tasks/interactivity-tasks/send-keys',
                        'client-user-interface/server/job-tasks/interactivity-tasks/wait',
                        'client-user-interface/server/job-tasks/interactivity-tasks/play-sound',                
                      ],
                    },
                    {
                    type: 'category',
                    label: 'Internal Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/internal-tasks/control',
                      'client-user-interface/server/job-tasks/internal-tasks/export-settings',
                      'client-user-interface/server/job-tasks/internal-tasks/set-job-variable',
                      'client-user-interface/server/job-tasks/internal-tasks/set-user-variable', 
                      'client-user-interface/server/job-tasks/internal-tasks/calculate-variable',
                      'client-user-interface/server/job-tasks/internal-tasks/remove-variable',  
                      'client-user-interface/server/job-tasks/internal-tasks/report',                     
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Active Directory Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/active-directory-tasks/create-ad-group',
                      'client-user-interface/server/job-tasks/active-directory-tasks/create-ad-object',
                      'client-user-interface/server/job-tasks/active-directory-tasks/create-ad-user',
                      'client-user-interface/server/job-tasks/active-directory-tasks/delete-ad-object',   
                      'client-user-interface/server/job-tasks/active-directory-tasks/get-ad-group-members',
                      'client-user-interface/server/job-tasks/active-directory-tasks/get-ad-object-path',
                      'client-user-interface/server/job-tasks/active-directory-tasks/get-ad-property',
                      'client-user-interface/server/job-tasks/active-directory-tasks/list-ad-object-paths',
                      'client-user-interface/server/job-tasks/active-directory-tasks/modify-ad-group',
                      'client-user-interface/server/job-tasks/active-directory-tasks/modify-ad-user',
                      'client-user-interface/server/job-tasks/active-directory-tasks/move-ad-object',
                      'client-user-interface/server/job-tasks/active-directory-tasks/rename-ad-object',
                      'client-user-interface/server/job-tasks/active-directory-tasks/set-ad-object-property',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'SNMP Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/snmp-tasks/snmp-get',
                      'client-user-interface/server/job-tasks/snmp-tasks/snmp-get-next',
                      'client-user-interface/server/job-tasks/snmp-tasks/snmp-get-bulk',
                      'client-user-interface/server/job-tasks/snmp-tasks/snmp-walk',
                      'client-user-interface/server/job-tasks/snmp-tasks/snmp-set',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Exchange Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/exchange-tasks/create-exchange-object',
                      'client-user-interface/server/job-tasks/exchange-tasks/get-exchange-object',
                      'client-user-interface/server/job-tasks/exchange-tasks/modify-exchange-object',
                      'client-user-interface/server/job-tasks/exchange-tasks/delete-exchange-object',
                      'client-user-interface/server/job-tasks/exchange-tasks/delete-exchange-objects',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Sharepoint Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/sharepoint-tasks/create-list',
                      'client-user-interface/server/job-tasks/sharepoint-tasks/delete-list',
                      'client-user-interface/server/job-tasks/sharepoint-tasks/describe-list',
                      'client-user-interface/server/job-tasks/sharepoint-tasks/get-list',
                      'client-user-interface/server/job-tasks/sharepoint-tasks/add-list-item',
                      'client-user-interface/server/job-tasks/sharepoint-tasks/update-list-item',
                      'client-user-interface/server/job-tasks/sharepoint-tasks/delete-list-item',
                      'client-user-interface/server/job-tasks/sharepoint-tasks/get-list-item',
                      'client-user-interface/server/job-tasks/sharepoint-tasks/upload-file',
                      'client-user-interface/server/job-tasks/sharepoint-tasks/download-file',
                      'client-user-interface/server/job-tasks/sharepoint-tasks/list-file',
                      'client-user-interface/server/job-tasks/sharepoint-tasks/delete-file',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Virtual Server Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/virtual-server-tasks/start-vm',
                      'client-user-interface/server/job-tasks/virtual-server-tasks/pause-vm',
                      'client-user-interface/server/job-tasks/virtual-server-tasks/reset-vm',
                      'client-user-interface/server/job-tasks/virtual-server-tasks/turn-off-vm',
                      'client-user-interface/server/job-tasks/virtual-server-tasks/save-vm-state',
                      'client-user-interface/server/job-tasks/virtual-server-tasks/check-vm-status',
                      'client-user-interface/server/job-tasks/virtual-server-tasks/list-vm-machines',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Dynamic CRM Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/dynamics-crm-tasks/overview',
                      'client-user-interface/server/job-tasks/dynamics-crm-tasks/get-entity',
                      'client-user-interface/server/job-tasks/dynamics-crm-tasks/create-entity',
                      'client-user-interface/server/job-tasks/dynamics-crm-tasks/update-entity',
                      'client-user-interface/server/job-tasks/dynamics-crm-tasks/delete-entity',
                      'client-user-interface/server/job-tasks/dynamics-crm-tasks/list-entity',
                      'client-user-interface/server/job-tasks/dynamics-crm-tasks/get-audit-data',
                      'client-user-interface/server/job-tasks/dynamics-crm-tasks/set-audit-status',
                      'client-user-interface/server/job-tasks/dynamics-crm-tasks/start-work-flow',
                      'client-user-interface/server/job-tasks/dynamics-crm-tasks/download-attachments',
                      'client-user-interface/server/job-tasks/dynamics-crm-tasks/upload-attachment',
                      'client-user-interface/server/job-tasks/dynamics-crm-tasks/delete-attachment',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Cloud Transfer Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/cloud-transfer-tasks/overview',
                      'client-user-interface/server/job-tasks/cloud-transfer-tasks/upload-file',
                      'client-user-interface/server/job-tasks/cloud-transfer-tasks/list-item',
                      'client-user-interface/server/job-tasks/cloud-transfer-tasks/download-file',
                      'client-user-interface/server/job-tasks/cloud-transfer-tasks/create-folder',
                      'client-user-interface/server/job-tasks/cloud-transfer-tasks/delete-item',
                      'client-user-interface/server/job-tasks/cloud-transfer-tasks/copy-move',
                      'client-user-interface/server/job-tasks/cloud-transfer-tasks/sync',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Amazon EC2 Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/overview',
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/start-instance',
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/launch-instance',
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/stop-instance',
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/terminate-instance',
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/reboot-instance',
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/list-instance',
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/list-security-group',
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/list-address',
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/list-volume',
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/list-snapshot',
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/delete-snapshot',
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/create-snapshot',
                      'client-user-interface/server/job-tasks/amazon-ec2-tasks/list-key-pairs',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Azure Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/azure-tasks/overview',
                      'client-user-interface/server/job-tasks/azure-tasks/start-vm',
                      'client-user-interface/server/job-tasks/azure-tasks/stop-vm',
                      'client-user-interface/server/job-tasks/azure-tasks/restart-vm',
                      'client-user-interface/server/job-tasks/azure-tasks/update-vm',
                      'client-user-interface/server/job-tasks/azure-tasks/create-vm',
                      'client-user-interface/server/job-tasks/azure-tasks/start-web-site',
                      'client-user-interface/server/job-tasks/azure-tasks/stop-web-site',
                      'client-user-interface/server/job-tasks/azure-tasks/restart-web-site',
                      'client-user-interface/server/job-tasks/azure-tasks/remove-web-site',
                      'client-user-interface/server/job-tasks/azure-tasks/create-web-site',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Office365 Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/office365-tasks/get-calendar-events',
                      'client-user-interface/server/job-tasks/office365-tasks/add-calendar-event',
                      'client-user-interface/server/job-tasks/office365-tasks/update-calendar-event',
                      'client-user-interface/server/job-tasks/office365-tasks/delete-calendar-event',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Hyper-V Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/hyper-v-tasks/overview',
                      'client-user-interface/server/job-tasks/hyper-v-tasks/list-vm',
                      'client-user-interface/server/job-tasks/hyper-v-tasks/start-vm',
                      'client-user-interface/server/job-tasks/hyper-v-tasks/stop-vm',
                      'client-user-interface/server/job-tasks/hyper-v-tasks/pause-vm',
                      'client-user-interface/server/job-tasks/hyper-v-tasks/suspend-vm',
                      'client-user-interface/server/job-tasks/hyper-v-tasks/resume-vm',
                      'client-user-interface/server/job-tasks/hyper-v-tasks/check-vm',
                      'client-user-interface/server/job-tasks/hyper-v-tasks/reset-vm',
                      'client-user-interface/server/job-tasks/hyper-v-tasks/create-snapshot',
                      'client-user-interface/server/job-tasks/hyper-v-tasks/apply-snapshot',
                      'client-user-interface/server/job-tasks/hyper-v-tasks/delete-snapshot',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'VMWare Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/vmware-tasks/overview',
                      'client-user-interface/server/job-tasks/vmware-tasks/start-vm',
                      'client-user-interface/server/job-tasks/vmware-tasks/stop-vm',
                      'client-user-interface/server/job-tasks/vmware-tasks/suspend-vm',
                      'client-user-interface/server/job-tasks/vmware-tasks/pause-vm',
                      'client-user-interface/server/job-tasks/vmware-tasks/resume-vm',
                      'client-user-interface/server/job-tasks/vmware-tasks/reset-vm',
                      'client-user-interface/server/job-tasks/vmware-tasks/get-vm-status',
                      'client-user-interface/server/job-tasks/vmware-tasks/create-vm-snapshot',
                      'client-user-interface/server/job-tasks/vmware-tasks/revert-to-vm-snapshot',
                      'client-user-interface/server/job-tasks/vmware-tasks/delete-vm-snapshot',
                      'client-user-interface/server/job-tasks/vmware-tasks/list-vm-snapshots',
                      'client-user-interface/server/job-tasks/vmware-tasks/delete-vm',
                      'client-user-interface/server/job-tasks/vmware-tasks/clone-vm',
                      'client-user-interface/server/job-tasks/vmware-tasks/install-tools',
                      'client-user-interface/server/job-tasks/vmware-tasks/register-vm',
                      'client-user-interface/server/job-tasks/vmware-tasks/unregister-vm',
                      'client-user-interface/server/job-tasks/vmware-tasks/list-vm',
                      'client-user-interface/server/job-tasks/vmware-tasks/guest-capture-screen',
                      'client-user-interface/server/job-tasks/vmware-tasks/guest-copy-file',
                      'client-user-interface/server/job-tasks/vmware-tasks/guest-rename-file',
                      'client-user-interface/server/job-tasks/vmware-tasks/guest-delete-file',
                      'client-user-interface/server/job-tasks/vmware-tasks/guest-directory-exists',
                      'client-user-interface/server/job-tasks/vmware-tasks/guest-file-exists',
                      'client-user-interface/server/job-tasks/vmware-tasks/guest-delete-directory',
                      'client-user-interface/server/job-tasks/vmware-tasks/guest-create-directory',
                      'client-user-interface/server/job-tasks/vmware-tasks/guest-create-temp-file',
                      'client-user-interface/server/job-tasks/vmware-tasks/guest-run-command',
                      'client-user-interface/server/job-tasks/vmware-tasks/guest-open-url',
                      'client-user-interface/server/job-tasks/vmware-tasks/guest-kill-process',
                      'client-user-interface/server/job-tasks/vmware-tasks/guest-list-process',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'MSMQ Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/msmq-tasks/overview',
                      'client-user-interface/server/job-tasks/msmq-tasks/send-message',
                      'client-user-interface/server/job-tasks/msmq-tasks/delete-message',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'PDF Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/pdf-tasks/overview',
                      'client-user-interface/server/job-tasks/pdf-tasks/add-footer-header',
                      'client-user-interface/server/job-tasks/pdf-tasks/concatenate',
                      'client-user-interface/server/job-tasks/pdf-tasks/split',
                      'client-user-interface/server/job-tasks/pdf-tasks/remove-page',
                      'client-user-interface/server/job-tasks/pdf-tasks/get-information',
                      'client-user-interface/server/job-tasks/pdf-tasks/convert',
                      'client-user-interface/server/job-tasks/pdf-tasks/get-field',
                      'client-user-interface/server/job-tasks/pdf-tasks/set-field',
                      'client-user-interface/server/job-tasks/pdf-tasks/encrypt',
                      'client-user-interface/server/job-tasks/pdf-tasks/decrypt',
                      'client-user-interface/server/job-tasks/pdf-tasks/sign',
                      'client-user-interface/server/job-tasks/pdf-tasks/clear-signature',
                      'client-user-interface/server/job-tasks/pdf-tasks/add-attachment',
                      'client-user-interface/server/job-tasks/pdf-tasks/get-attachment',
                      'client-user-interface/server/job-tasks/pdf-tasks/delete-attachment',
                      'client-user-interface/server/job-tasks/pdf-tasks/replace-text',
                      'client-user-interface/server/job-tasks/pdf-tasks/search-text',
                      'client-user-interface/server/job-tasks/pdf-tasks/insert-pages',
                    ],
                  },
                  'client-user-interface/server/job-tasks/iis-tasks/iis-tasks',
                  {
                    type: 'category',
                    label: 'SAP Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/sap-tasks/overview',
                      'client-user-interface/server/job-tasks/sap-tasks/r3-job-execute',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Informatica Tasks',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/job-tasks/informatica-tasks/run-job',
                    ],
                  },
                    'client-user-interface/server/task-main-settings-execution-context',
                    'client-user-interface/server/task-conditions',
                    'client-user-interface/server/task-task-type',
                    'client-user-interface/server/task-on-error',
                    'client-user-interface/server/task-timeout',
                    'client-user-interface/server/task-notifications',
                    'client-user-interface/server/task-flow',
                    'client-user-interface/server/task-exit-code-collection',
                    'client-user-interface/server/task-output-and-result',
                    ],
                  },
                  'client-user-interface/server/job-timeout',
                  'client-user-interface/server/job-notifications',
                  'client-user-interface/server/job-flow',
                  'client-user-interface/server/job-result',
                  'client-user-interface/server/job-agent-distribution',
                  'client-user-interface/server/roi-return-on-investment',
                ],
              },
              'client-user-interface/server/jobs-failed-jobs',
              'client-user-interface/server/jobs-running-jobs',
              'client-user-interface/server/global-certificates',
              {
                type: 'category',
                label: 'Global - Conditions',
                collapsed: true,
                items: [
                  'client-user-interface/server/global-conditions',
                  'client-user-interface/server/global-main-settings',
                  {
                    type: 'category',
                    label: 'Conditions - Conditions',
                    collapsed: true,
                    items: [
                      'client-user-interface/server/conditions-conditions',
                      'client-user-interface/server/condition-visualcron',
                      'client-user-interface/server/condition-file',
                      'client-user-interface/server/condition-folder',
                      'client-user-interface/server/condition-process',
                      'client-user-interface/server/condition-dot-net',
                    ],
                  },
                  'client-user-interface/server/conditions-actions',
                ],
              },
              {
                type: 'category',
                label: 'Global - Connections',
                collapsed: true,
                items: [
                  'client-user-interface/server/global-connections',
                  'client-user-interface/server/connection-ftp',
                  'client-user-interface/server/connection-sftp',
                  'client-user-interface/server/connection-scp',
                  'client-user-interface/server/connection-ssh',
                  'client-user-interface/server/connection-tcp',
                  'client-user-interface/server/connection-smtp',
                  'client-user-interface/server/connection-pop3',
                  'client-user-interface/server/connection-imap4',
                  'client-user-interface/server/connection-exchange-ews',
                  'client-user-interface/server/connection-exchange-webdav',
                  'client-user-interface/server/connection-webdav',
                  'client-user-interface/server/connection-sql',
                  'client-user-interface/server/connection-ssrs',
                  'client-user-interface/server/connection-amazon',
                  'client-user-interface/server/connection-microsoft-azure',
                  'client-user-interface/server/connection-dropbox',
                  'client-user-interface/server/connection-google-drive',
                  'client-user-interface/server/connection-google-cloud',
                  'client-user-interface/server/connection-onedrive',
                  'client-user-interface/server/connection-office365',
                  'client-user-interface/server/connection-box',
                  'client-user-interface/server/connection-visualcron',
                  'client-user-interface/server/connection-sharepoint',
                  'client-user-interface/server/connection-xendapp',
                  'client-user-interface/server/connection-pushbullet',
                  'client-user-interface/server/connection-telegram',
                  'client-user-interface/server/connection-twitter',
                  'client-user-interface/server/connection-crystalreports',
                  'client-user-interface/server/connection-vmware',
                  'client-user-interface/server/connection-dynamics-crm',
                  'client-user-interface/server/connection-as400',
                  'client-user-interface/server/connection-sap',
                  'client-user-interface/server/connection-amqp',
                  'client-user-interface/server/connection-slack',
                  'client-user-interface/server/connection-informatica',
                  'client-user-interface/server/connection-telnet',
                  'client-user-interface/server/connection-facebook',
                  'client-user-interface/server/connection-peoplesoft',
                  'client-user-interface/server/connection-ibm-cognos-analytics',
                ],
              },
              'client-user-interface/server/global-credentials',
              'client-user-interface/server/global-network-drives',
              'client-user-interface/server/global-notifications',
              'client-user-interface/server/global-pgp-key-rings',
              'client-user-interface/server/global-time-exceptions',
              {
                type: 'category',
                label: 'Global Variables',
                collapsed: true,
                items: [
                  'client-user-interface/server/global-variables',
                  'client-user-interface/server/global-date-time-variables',
                ],
              }, 
              'client-user-interface/server/global-task-repository',
              'client-user-interface/server/information-log',
              'client-user-interface/server/information-server-info',
              'client-user-interface/server/information-license',
          ],
        },
        {
          type: 'category',
          label: 'Servers',
          collapsed: true,
          items: [
            'client-user-interface/servers/servers',
            'client-user-interface/servers/servers-mft',
            'client-user-interface/servers/sync-server-objects',
            {
              type: 'category',
              label: 'Servers - Execution Distribution',
              collapsed: true,
              items: [
                'client-user-interface/servers/servers-execution-distribution',
                'client-user-interface/servers/load-balancer',
                'client-user-interface/servers/broker-server',
                'client-user-interface/servers/execution-distribution',
                'client-user-interface/servers/load-balancing-flows',
                'client-user-interface/servers/load-balancing-conditions',
              ],
            }, 
          ],
        },
        {
          type: 'category',
          label: 'Tools',
          collapsed: true,
          items: [
            'client-user-interface/tools/overview',
            'client-user-interface/tools/explore-file-explorer',
            'client-user-interface/tools/explore-sql-explorer',
            'client-user-interface/tools/explore-connection-explorer',
            'client-user-interface/tools/server-monitor',
            'client-user-interface/tools/task-manager',
            'client-user-interface/tools/report-print-job-report',
            {
              type: 'category',
              label: 'Objects',
              collapsed: true,
              items: [
                'client-user-interface/tools/objects',
                'client-user-interface/tools/object-relations',
                'client-user-interface/tools/object-search',
                'client-user-interface/tools/object-replace-merge',
              ],
            }, 
            {
              type: 'category',
              label: 'Objects - Audit Log',
              collapsed: true,
              items: [
                'client-user-interface/tools/objects-audit-log',
                'client-user-interface/tools/audit-log-versions',
              ],
            }, 
              'client-user-interface/tools/schedule-calendar',
              'client-user-interface/tools/flow-chart-flow-chart',
              'client-user-interface/tools/gantt-chart',
          ],
        },
        'client-user-interface/reports',
        {
          type: 'category',
          label: 'Interface',
          collapsed: true,
          items: [
            'client-user-interface/interface/overview',
            'client-user-interface/interface/columns-group-jobs',
            'client-user-interface/interface/columns-set-columns',
            'client-user-interface/interface/columns-expand-all',
            'client-user-interface/interface/filter-grid-filter',
            'client-user-interface/interface/filter-clear-filter',
          ],
        }, 
        {
          type: 'category',
          label: 'Help',
          collapsed: true,
          items: [
            'client-user-interface/help/overview',
            'client-user-interface/help/internal-show-documentation',
            'client-user-interface/help/internal-api',
            'client-user-interface/help/external-forum',
            'client-user-interface/help/external-contact-us',
            'client-user-interface/help/external-tutorials',
          ],
        },
        {
          type: 'category',
          label: 'About',
          collapsed: true,
          items: [
            'client-user-interface/about/overview',
            'client-user-interface/about/about-visualcron',
            'client-user-interface/about/feedback-suggest-a-feature',
          ],
        },
      ],
    },
        {
          type: 'category',
          label: 'Toolbar',
          collapsed: true,
          items: [
            'client-user-interface/toolbar/overview',
            'client-user-interface/toolbar/server-selection',
            'client-user-interface/toolbar/manage-servers',
            'client-user-interface/toolbar/disconnect-connect',
            'client-user-interface/toolbar/add-job',
            'client-user-interface/toolbar/edit-job',
            'client-user-interface/toolbar/clone-job',
            'client-user-interface/toolbar/delete-job',
            'client-user-interface/toolbar/run-job',
          ],
        },
        {
          type: 'category',
          label: 'Server/Group/Job/Task Area',
          collapsed: true,
          items: [
            'client-user-interface/server-group-job-task-area/overview',
            'client-user-interface/server-group-job-task-area/server-heading-server-info',
            {
              type: 'category',
              label: 'Job List',
              collapsed: true,
              items: [
                'client-user-interface/server-group-job-task-area/job-list/overview',
                'client-user-interface/server-group-job-task-area/job-list/add-job',
                'client-user-interface/server-group-job-task-area/job-list/add-task-to-job',
                'client-user-interface/server-group-job-task-area/job-list/edit-job',
                'client-user-interface/server-group-job-task-area/job-list/clone-job',
                'client-user-interface/server-group-job-task-area/job-list/delete-job',
                'client-user-interface/server-group-job-task-area/job-list/delete-selected-jobs',
                'client-user-interface/server-group-job-task-area/job-list/cut-job',
                'client-user-interface/server-group-job-task-area/job-list/copy-job',
                'client-user-interface/server-group-job-task-area/job-list/paste-job',
                'client-user-interface/server-group-job-task-area/job-list/run-job',
                'client-user-interface/server-group-job-task-area/job-list/triggers',
                'client-user-interface/server-group-job-task-area/job-list/run-task',
                'client-user-interface/server-group-job-task-area/job-list/stop-job',
                'client-user-interface/server-group-job-task-area/job-list/activate-deactivate-job',
                'client-user-interface/server-group-job-task-area/job-list/reset-job',
                'client-user-interface/server-group-job-task-area/job-list/job-log',
                'client-user-interface/server-group-job-task-area/job-list/task-log',
                'client-user-interface/server-group-job-task-area/job-list/audit-log',
                'client-user-interface/server-group-job-task-area/job-list/versions',
                'client-user-interface/server-group-job-task-area/job-list/object-relations',
                'client-user-interface/server-group-job-task-area/job-list/show-statistics',
                'client-user-interface/server-group-job-task-area/job-list/show-flow-chart',
              ],
            },
            'client-user-interface/server-group-job-task-area/task-list',   
          ],
        },
        'client-user-interface/job-folders',
        {
          type: 'category',
          label: 'Status Bar',
          collapsed: true,
          items: [
            'client-user-interface/status-bar',
            'client-user-interface/client-events',
            'client-user-interface/server-name',
            'client-user-interface/server-time',
          ],
        },         
      ],
    },
    'debugging-and-logging',
    'security',
    {
      type: 'category',
      label: 'Commands, Scripts, and Third Party Tools',
      collapsed: true,
      items: [
        'commands/commands-scripts-third-party-tools',
        'commands/commands-and-batch-files',
        'commands/scripts',
      ],
    },    
    {
      type: 'category',
      label: 'FAQ',
      collapsed: true,
      items: [
        'faq/install-upgrade-procedure',
        'faq/visualcron-using-so-much-memory',
        'faq/installation-file-so-big',
        'faq/firewall-warn-internet-access',
        'faq/add-edit-delete-lag-time',
        'faq/support-visualcron',
        'faq/move-visualcron-active-license-new-server',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: true,
      items: [
        'examples/setting-a-job-to-run-every-second-or-five-minutes',
        'examples/using-arguments-parameters-for-a-job',
      ],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      collapsed: true,
      items: [
        'troubleshooting/job-does-not-run',
        'troubleshooting/i-cant-start-visualcron',
        'troubleshooting/i-cant-connect-to-visualcron-server',
        'troubleshooting/forgot-my-password',
        'troubleshooting/missing-system-file-perfc009',
        'troubleshooting/i-cant-open-visualcron-documentation',
        'troubleshooting/i-cant-download-visualcron',
        'troubleshooting/windows-98-me-errors',
        'troubleshooting/client-timeouts',
        'troubleshooting/windows-command-does-not-execute',
        'troubleshooting/settings-do-not-work',
        'troubleshooting/external-link-errors',
        'troubleshooting/installation-errors',
        'troubleshooting/wmi-is-broken',
        'troubleshooting/visualcron-service-does-not-start-automatically',
        'troubleshooting/upgrade-setup-fails',
        'troubleshooting/server-mode-ssl-certificate',
        'troubleshooting/error-114-in-sftp-task',
        'troubleshooting/uninstall-fails',
        'troubleshooting/file-not-found-access-denied',
        'troubleshooting/error-loading-server-settings',
      ],
    },
    {
      type: 'category',
      label: 'Definitions',
      collapsed: true,
      items: [
        'general-definitions',
        'visualcron-specific-definitions',
        'documentation-format',
      ],
    },
  ],
};
